### ISSUE TITLE
Est-ce-qu'on gere d'autres types de Transfer-Encoding ? 

### ISSUE THREAD

**Issue by NicolasReaItalo** [qgiraux/WebServ#13]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

**Comment by qgiraux** [comment]
je pense qu'on devrait d'abord se concentrer sur finir ce qui est obligatoire dans le sujet (pour ma part, POST chunked, et les CGI). Apres, lors de la phase de polish et debug, pourquoi pas si on le sent bien
