### ISSUE TITLE
Une location vide entraine une ParsingError()

### ISSUE THREAD

**Issue by NicolasReaItalo** [qgiraux/WebServ#26]
server {
	listen 127.0.0.1:8080;
	server_name localhost;
	root ./tests/03_server_simple/server-files;

	location /index_set{
		index index.html;
	}

	# <- cause une parsing error
	location /index_not_set{
	}

	location /autoindex_ok{
		autoindex on;
	}
	location /autoindex_ok{
		autoindex off;
	}
}

**Comment by jerperez42** [comment]
fixed
